Feature task1 create user service
MMMMr1/digital_wallet pull request #1
Opened 2023-10-25 10:12 UTC by MMMMr1

2023-10-27 14:28 UTC, Avokado-an requested changes

2023-10-27 14:28 UTC, Avokado-an commented on user-service/build.gradle
> +dependencies {
по этой линке можешь увидеть, какие версии зависимостей по дефолту ставит спринг бут
https://docs.spring.io/spring-boot/docs/3.1.5/reference/html/dependency-versions.html
советую на них ориентироваться, тк это уже проверенные версии, что между собой полностью совместимы и без неожиданностей (версию можно менять с 3.1.5 на любую другую по ссылке и увидеть автоматом поставленную версию). Еще если увидишь проблемы с несовместимостью версий в будущей, используй градловскую команду для построения дерева зависимостей, оч полезно может быть

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/configuration/PasswordEncoder.java
> +//@Configuration
перед тем как создавать пул реквест лучше всегда убрать ненужные классы, комменты и тд
Как понимаю тут эта конфигурация тебе не нужна

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/mapper/UserMapper.java
> +    @Mapping(target = "uuid", expression = "java(java.util.UUID.randomUUID())")
интересный момент. Во время тестирования часто всякие поля по типу created_at и тд (которые генерятся через статические вызовы методов) вызывают проблемы, тк статические вызовы мокать сложно, в итоге приходится добавлять зависимости по типу павер мока, чтобы норм тестить или тестить через костыли. Советую логику по генерации этих полей вынести из маппера в сервис + создать утилитный класс, который будет оборачивать статические вызовы, чтобы при тестировании ты могла его супер легко замокать. Ну и в общем плане маппер для передачи значений, но не для генерации, генерацию оставь уже сервисам

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserCreateDto.java
> +                             @UserStatusValid(anyOf = {UserStatus.ACTIVATED,UserStatus.DEACTIVATED,UserStatus.WAITING_ACTIVATION})
хорошо сделала, что добавила  собственный валидатор. Советую немного только его переделать. Сделать общий валидатор для енамов, куда ты передаешь класс енама, а из него достаётся автоматом список доступных щначений (в initialize методе валидатора можешь настроить это вытаскивание значений для валидации). Тогда получится универсальный класс, что-то типо @ValidatedEnum(CustomEnum.class, message)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserRegistrationDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
снейк кейс разве не будет дефолтным значением для джейсон нейминга? Сам не проверял, но учитывая автоматический маппинг не уверен, нужно ли здесь это уточнение

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserRegistrationDto.java
> +                                   @Pattern(regexp = REGEXP_VALIDATE_EMAIL,
если определенные правила валидации часто используешь, то можешь опять же отдельный валидор создать, типо @ValidEmail, @ValidPhoNumber, тип такого. Иначе много дублирования кода получается для одинаковых действий

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/response/UserInfoDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
тот же коммент по надобности указания нейминг стратегии

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/response/VerificationDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
ну и тут тоже по стратегии вопрос, нужна ли

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    @Column(name = "uuid", nullable = false)
как опция ты можешь это значение еще генерить автоматически самой базой. Но надо учитывать, что при тестировании слоя бд будут тесты чуть костылявые, но не придется в бизнес логике прописывать. Оба варианта рабочие, скорее по личным предпочтениям надо смотреть

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    @Enumerated(EnumType.STRING)
для отсутствия дубляжа целых строк в бедешке, можешьь тип ORDINAL поставить, тогда чисто цифры-идентификаторы будут сохраняться

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    private Set<UserRole> role;
тут вопрос по бизнес логике, актуально ли тебе делать систему из различных ролей или ты можешь просто одну единственную сохоранять (юсер/админ/суперадмин), где каждая следующая роль может делать всё, что и предыдущая + еще что-то. Если же у тебя будет комплексная система пермишенов, где разные роли никак друг с другом по логике не подвязаны, то тогда можешь оставлять сет

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    private Instant dtCreate;
это тоже можно автоматом генерить

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    private Instant dtUpdate;
если это та @Version что я думаю, то она нужна для механизма оптимистичного локинга. Не знаю, может ты потом для этого используешь, но не уверен, что оно тебе в данный момент надо + это значение можно тоже автоматически генерить через аннотации хиьера, как и пару полей выше

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +public class User {
по неймингу, лучше в названии класса оставляй информацию о том, к чему он пренадлежит. Если энтити - то UserSchema/UserEntity, если это объект бизнес логики, то Bo в конце, например или Dto или еще что-то. В общем добавляй постфикссы, с помощью которых можно понять пренадлеэность класса к слою архитектуры

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/Verification.java
> +public class Verification {
здесь тот же коммент по неймингу + напоминаю про автоматическую генерацию (использовать ее не обязываю, тут твой выбор, тк есть свои плюсы и минусы, но хочу, чтобы не забывалось эта опция)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/error/ExceptionErrorDTO.java
> +    public String getLogref() {
геттеры через ломбок, сами не пишем

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/error/ExceptionListDTO.java
> +    public ExceptionListDTO() {
вместо самостоятельного написания исопльзуй аннотации ломбока, тут все кроме 1 конструктора можно заменить аннотациями

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/error/ExceptionStructuredDTO.java
> +public class ExceptionStructuredDTO {
тут тоже ломбок

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/exception/InvalidVersionException.java
> +    public InvalidVersionException() {
тут тоже ломбок

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/exception/UserAlreadyExistException.java
> +    public UserAlreadyExistException() {
я больше про ломбок комментов над обычными жто оставлять не буду, но ты в остальных местах тоже его исопльзуй

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/repository/api/AuthenticationRepository.java
> +public interface AuthenticationRepository extends CrudRepository<Verification, String> {
поменяй нейминг репозитория, чтообы он лучше соответствовал энтити, с которой работает (что-то типа VerificationRepository / VerificationEntityRepository)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/repository/api/AuthenticationRepository.java
> +public interface AuthenticationRepository extends CrudRepository<Verification, String> {
а еще можешь расписать, как у тебя должна происходить работа верификации, что для нее существует отдельная таблица в базе и тд, можешь просто под этим комментом

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        UserInfoDto userInfoDto = userService.create(
я помню у тебя был маппер, вот здесь как раз лучше через маппер это логику сделай, иначе нагруженный код получается

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        String code = UUID.randomUUID().toString();
вот тут как раз можно исопльзовать дополнительный утилитный класс для обертки статических методов, чтобы упростить написание тестов в будущем

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        Verification verification = new Verification();
тут советую выделить логику создания этого объекта в отдельный мметод, чтобы разгрузить этот, сейчас он перегружен, что вроде и данные сохраняем в базу, и маппинг значений производим, и объект руками создаем. Лучше как минимум часть с созданием объекта вынести в отдельный метод, в который передаешь аргументы и получаешь готовый объект

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +@Transactional(readOnly = true)
нужна ли тебе транзакция над всеми методами? Лучше если тебе что-то нужно оставить это только в том методе, где надо. Другими словами сузить пространство, где этот функционал используется (например оставить @transactional только там, где совсем необходимо)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +    @Transactional
у тебя уже стоит эта аннотация над всем классом. Тут либо только над нужными методами оставлять, либо только над всем классом, но и там, и там не стоит. Я бы предпочел оставлять только надо нужным методом, тк не всегда тебе транзакция нужна

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +    public void verify(String code, String mail) {
более подробное имя для мметода, чтобы было понятно, как происходит верификации (например, verifyUser или еще что-то, тк так непонятно, что верифицируется)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +    public void verify(String code, String mail) {
чет я с выводами поспешил, в принципе понятно, что в методе происходит, но лучше имя поменйя, чтобы оно лучше отображало логику за этим методом, тк verify ни о чем не говорит, тк это общий концепт

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        if(code.equals(verificationCode.getCode())) {
тут можешь выделить в отдельный метод, где чекается, равны ли коды, если нет, то кидается эксепшн. Тогда в твоем мметоде будет только вызов условного isCodeValid() а потом просто будет идти код без дополнительного наслоения ифов

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +    public void login(@Validated UserLoginDto userLoginDto) {
в такой ситуации ты разве уже не ожидаешь уже валидные дтошки? Как правило ты валидируешь их spring-validator библиотекой на уровне контроллера этими же аннотациями, а потом в сервисах уже спокойно используешь и не волнуешься

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +    }
не забывай комбинацию ctrl+alt+l для форматирования кода, а тут поставь дополнительный line-break, чтобы покрасивше было

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +            throw new ValidationUserException("User with mail {" + user.getMail() + " } is not ACTIVATED");
я последний год на котлине писал, так что не уверен до конца, но разве в 17 джаве нет более красивого способа конкатенации строк, чем через плюсики? Тут могу быть не прав, тк сильно к котлину уже привык

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +@Transactional(readOnly = true)
тот же вопрос по @transactional использованию

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        // если юзер, то при регистрации автоматически создаем ему кошелек - счет. Как один из возможных вариантов
всегда комменты только на инглише, русский ни в каком виде лучше не оставляй, тк даже если через год какой-нибудь заказчик будет проверять твой гит, то будет поприятнее, если всё уже полностью на английском

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (userRepository.existsByMail(userDto.mail()) || userRepository.existsByMobilePhone(userDto.mobilePhone())){
здесь можешь вынести в отдельный мметод, который может кинуть эксепшн

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        return userMapper.toUserInfo(user);
лучше сразу зачейни эти методы без создания отдельной переменной, сразу возвращая данные

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +    @Transactional
опять же вопрос о том, где тебе нужны транзакции, а где нет

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
не упоянул в другом месте, но лучше переименуй dt (как понимаю dateTime) в createdAt, updatedAt
сокращения сильно снижают читаемость кода

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
ну а еще опять же просится в отдельный метод

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        user.setRole(userDto.role());
тут просится маппер

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +                .map(userMapper::toUserInfo);
вот тут шикарный пример красивого маппинга. Лаконично и понятно, вот супер хороший вариант, как это красиво делать в остальных местах можно (куда конечно функциональщину получится засунуть)

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +    @Transactional
про неконсистентное испольлзования @Transactional я дальше писать не буду, но важно пересмотреть где оно тебе нужно, а где нет, тк похоже на то, что над всем методом не так то и нужно осталять аннотацию

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
просится отдельный метод

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
еще не очень понимаю, в чем уть использования версии здесь, можешь рассказать, для чего ты ее добавляла?

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +    public User findByMail(String mail) {
не очень понимаю, ты везде возвращала дто из методов сервиса (что и правильно), а здесь вернула объект, что работает с базой данных. Для этого есть причина? Если нет, то замапь его тут тоже на userInfoDto
вот пример как красиво сделать (тут котлин если что)
return repository.findById(id)
            .map(entity::toBusinessObject)
            .orElseThrow {
                EntityNotFoundException("not found")
            }

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/api/AuthenticationService.java
> +    void verify(String code,String mail);
ctrl+alt+l

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/validator/UserRoleValidator.java
> +//    @Override
коммент перед пул реквестом либо удаляем, либо имплементируем, либо оставляем хорошо описанный TODO

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/validator/UserStatusValidator.java
> +//    @Override
тож самое про комменты

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/validator/util/jackson/CustomInstantConverter.java
> +    public static class Serializer extends StdConverter<Instant, Long> {
тебе точно нужен этот класс? Выглядит как многовато дополнительной логики со статическим эмбеддед классом, чтобы простую логику так указать

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/ExceptionGlobal.java
> +        return ResponseEntity.status(HttpStatus.CONFLICT)
можешь создание респонс энтити выделить в отдельный класс, куда передаешь статус и месседж, чуть покрасивше будет

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/AuthenticationController.java
> +@Slf4j
лайн брейк

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/AuthenticationController.java
> +import org.springframework.web.bind.annotation.*;
точнее тут лайн брейк

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/AuthenticationController.java
> +    @RequestMapping(path = "/registration", method = RequestMethod.POST)
лучше сразу укажи пост маппинг, чтобы отдельно метод не указывать, так лаконичнее

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/AuthenticationController.java
> +public class AuthenticationController {
между методами класса ставь лайн брейки, чтоб покрасивше было

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/AuthenticationController.java
> +//    @RequestMapping(path = "/details", method = RequestMethod.GET)
та же штука про комменты

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/UserController.java
> +import java.util.UUID;
лайн брейк

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/UserController.java
> +    @RequestMapping(method = RequestMethod.POST)
про маппинг дальше писать не буду, просто этот момент поправь во всех местах

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/UserController.java
> +        Pageable paging = PageRequest.of(page, size);
ты можешь напрямую получать @pageable объект в контроллере без доп маппинга, погугли, там изи

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.OK)
тебе на самом деле здесь нет смысла оборачивать респонс в ResponseEntity, тк там и так 200 статус код, так что возвращай напрямую объекты

2023-10-27 14:28 UTC, Avokado-an commented on user-service/src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/db.changelog-2.0.sql
уже ликвидбейс добавила, это молодец

2023-10-28 10:41 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserRegistrationDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
проверила, по дефолту названия как в Dto без "_" : 
![image](https://github.com/MMMMr1/digital_wallet/assets/95496893/8eba25d8-7af4-46d8-be53-c240a29f627b)

2023-10-29 18:11 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/repository/api/AuthenticationRepository.java
> +public interface AuthenticationRepository extends CrudRepository<Verification, String> {
При регистрации пользователю на почту будет отправляться ссылка с кодом. Код и mail сохраняются в отдельную таблицу в БД (app.verification). 
При переходе по ссылке пользователь будет обращаться в контроллер авторизаций (метод verify). Далее сервис производит верификацию пользователя:
1. проверяем, есть ли в таблице такой email, при отсутствии выбрасываем ошибку
2. если есть сверяем код
3. обращаемся в user service и меняем статус пользователя на ACTIVATED
4. удаляем mail и code из таблицы  (app.verification)

2023-10-29 18:33 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +            throw new ValidationUserException("User with mail {" + user.getMail() + " } is not ACTIVATED");
Есть способ через метод concat(). Но мне кажется, что через + более читаемо
@Test
void whenUsingConcatToMultipleStringConcatenation_thenAssertEquals() {
    String stringOne = "Hello";
    String stringTwo = "World";
    String stringThree = ", in Jav";
    stringOne = stringOne.concat(" ").concat(stringTwo).concat(stringThree).concat("@");
    assertEquals("Hello World, in Jav@", stringOne);
}
есть еще String.join
@Test
void whenUsingStringJoin_thenAssertEquals() {
    String stringOne = "Hello";
    String stringTwo = " World";
    assertEquals("Hello World", String.join("", stringOne, stringTwo));
}

2023-10-30 11:06 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserCreateDto.java
> +                             @UserStatusValid(anyOf = {UserStatus.ACTIVATED,UserStatus.DEACTIVATED,UserStatus.WAITING_ACTIVATION})
+

2023-10-30 18:18 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    @Column(name = "uuid", nullable = false)
оставила в бизнес логике

2023-10-30 18:19 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/model/entity/User.java
> +    private Instant dtUpdate;
оставила аннотацию @Version на entity

2023-10-30 18:19 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/model/entity/Verification.java
> +public class Verification {
имя поменяла

2023-10-30 18:19 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/repository/api/AuthenticationRepository.java
> +public interface AuthenticationRepository extends CrudRepository<Verification, String> {
имя поменяла

2023-10-30 18:20 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        String code = UUID.randomUUID().toString();
создала утил классы

2023-10-30 18:20 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        if(code.equals(verificationCode.getCode())) {
вынесла в отдельный метод

2023-10-30 18:20 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/AuthenticationServiceImpl.java
> +        Verification verification = new Verification();
вынесла в отдельный метод

2023-10-30 18:21 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (userRepository.existsByMail(userDto.mail()) || userRepository.existsByMobilePhone(userDto.mobilePhone())){
вынесла в отдельный метод

2023-10-30 18:21 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        return userMapper.toUserInfo(user);
зачейнила

2023-10-30 18:22 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
переименовала поля, создала отдельный метод, который выбрасывает ошибку

2023-10-30 18:22 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        user.setRole(userDto.role());
использовала маппер

2023-10-30 18:23 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +        if (user.getDtUpdate().toEpochMilli() != version.toEpochMilli()) {
удалила версию на всех уровнях, кроме бд

2023-10-30 18:24 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/service/UserServiceImpl.java
> +    public User findByMail(String mail) {
метод использовал другой сервис. В данный момент, везде возвращаю дто, просто делаю конвертации (entity<->dto)

2023-10-30 18:29 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/validator/util/jackson/CustomInstantConverter.java
> +    public static class Serializer extends StdConverter<Instant, Long> {
удалила

2023-10-30 18:30 UTC, MMMMr1 commented on user-service/src/main/java/com/michalenok/wallet/web/ExceptionGlobal.java
> +        return ResponseEntity.status(HttpStatus.CONFLICT)
класс не создавала, провела оптимизацию кода)

2023-11-08 14:56 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/dto/request/UserRegistrationDto.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
значит вопрос снят

2023-11-08 14:56 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/model/entity/UserEntity.java
> +    @Enumerated(EnumType.STRING)
тут можешь ordinal поставить, чтобы лишние данные не хранились

2023-11-08 14:56 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/util/CreationUserUtil.java
> +    public Instant generateTimeUpdateAt() {
лучше создай один метод, который будет генерить нынешнее время, и исопльзуй его в обоих местах. Условно generateCurrentInstant

2023-11-08 14:56 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/service/util/VerificationUserUtil.java
> +    public String generateCode() {
и этот класс тебе не нужен. Ты либо сделай 2 раздельные утилиты TimeGenerationUtil и UuidUtil, либо 1 класс, которым все пользуются. Так у тебя получается дублирование кода ненужное. Лучше сделай первый вариант, что я тут описал с разделением утилит по их назначению

2023-11-08 14:56 UTC, Avokado-an commented on user-service/src/main/java/com/michalenok/wallet/web/controller/UserController.java
> +     * this method creates user with all data. Used by Admin
я думаю тут  джава док излишен. Можешь перенести в интерфейс сервиса, тк он бизнес логику выполняет

2023-11-10 07:59 UTC, MMMMr1 commented
user - service with crud operation using swagger, liqubase

2023-11-10 08:00 UTC, merged